### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by aliva-ksu** [leeyeehoo/CSRNet-pytorch#103]
Traceback (most recent call last):
  File "/content/CSRNet-pytorch/train.py", line 230, in <module>
    main()        
  File "/content/CSRNet-pytorch/train.py", line 92, in main
    train(train_list, model, criterion, optimizer, epoch)
  File "/content/CSRNet-pytorch/train.py", line 131, in train
    for i,(img, target)in enumerate(train_loader):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/CSRNet-pytorch/dataset.py", line 33, in __getitem__
    img,target = load_data(img_path,self.train)
TypeError: cannot unpack non-iterable NoneType object

Facing this error while training CSRNet on custom dataset. Can anyone explain how to resolve it?

**Comment by xcaizewu** [comment]
你的json路径错了吧 所以train_list为None
